[tool.ruff]
# Enable pycodestyle (E), pyflakes (F), and bugbear (B) rules
select = ["E", "F", "B"]

# Ignore line length violations--Black handles those
line-length = 88
ignore = ["E501"]

target-version = "py37"

src = ["src", "tests"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"


[tool.black]
line-length = 88
target-version = ["py37"]


[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    py37
    py37-lint
    py38
    py39
    py310
    py311

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
deps = -rrequirements-dev.txt
commands =
    pytest {posargs}

[testenv:py37-lint]
basepython = python3.7
changedir = {toxinidir}
commands =
    black --check src setup.py tests
    ruff src setup.py tests
"""
